name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.6.0
  - ipython=8.15.0
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - cookiecutter=1.7.3
  - hydra-core=1.3.2
  - matplotlib=3.7.2
  - pandas=2.0.3
  - git=2.40.1
  - pip=23.2.1
  - ipykernel=6.25.0
  - pandas-profiling=2.9.0
  - seaborn=0.12.2
  - pip:
      - wandb==0.15.10
