name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook=6.5.4
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - pandas-profiling=2.9.0
  - pyarrow=11.0.0
  - ipykernel=6.25.0
  - pip:
      - wandb==0.15.10